# Generated by Django 3.0.4 on 2020-04-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openweatherdata',
            name='beaufort',
        ),
        migrations.RemoveField(
            model_name='openweatherdata',
            name='direction',
        ),
    ]
