# Generated by Django 3.0.4 on 2020-04-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200415_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteodata',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='openweatherdata',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
