# Generated by Django 3.0.4 on 2020-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200415_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('city_id', models.CharField(max_length=200)),
            ],
        ),
    ]
