# Generated by Django 3.0.4 on 2020-05-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20200429_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_id',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='langitude',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='city_state',
            new_name='state',
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.CharField(default=34, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default=43, max_length=200),
            preserve_default=False,
        ),
    ]
