# Generated by Django 3.0.4 on 2020-05-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20200502_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='langitude',
            new_name='latitude',
        ),
    ]
